In [18]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
# Read the dataset
df = pd.read_excel(r"C:\Users\Yap Hui Qing\Documents\number of deaths by risk factor.xlsx")
df.head()

,Entity,Code,Year,Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number),...,Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,1990,3169,25633,1045,7077,356,3185,3702,...,9518,2798,4825,174,389,2016,7686,107,2216,564
1,Afghanistan,AFG,1991,3222,25872,1055,7149,364,3248,4309,...,9489,3254,5127,188,389,2056,7886,121,2501,611
2,Afghanistan,AFG,1992,3395,26309,1075,7297,376,3351,5356,...,9528,4042,5889,211,393,2100,8568,150,3053,700
3,Afghanistan,AFG,1993,3623,26961,1103,7499,389,3480,7152,...,9611,5392,7007,232,411,2316,9875,204,3726,773
4,Afghanistan,AFG,1994,3788,27658,1134,7698,399,3610,7192,...,9675,5418,7421,247,413,2665,11031,204,3833,812

In [20]:
# DataFrame
df1 = pd.DataFrame(df)
print(df1)

           Entity Code  Year  \
0     Afghanistan  AFG  1990
1     Afghanistan  AFG  1991
2     Afghanistan  AFG  1992
3     Afghanistan  AFG  1993
4     Afghanistan  AFG  1994
...           ...  ...   ...
6835     Zimbabwe  ZWE  2015
6836     Zimbabwe  ZWE  2016
6837     Zimbabwe  ZWE  2017
6838     Zimbabwe  ZWE  2018
6839     Zimbabwe  ZWE  2019

      Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number)  \
0                                                  3169
1                                                  3222
2                                                  3395
3                                                  3623
4                                                  3788
...                                                 ...
6835                                               2835
6836                                               2781
6837                                               2700
6838                                               2669
6839                                               2680

      Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number)  \
0                                                 25633
1                                                 25872
2                                                 26309
3                                                 26961
4                                                 27658
...                                                 ...
6835                                              11483
6836                                              11663
6837                                              11819
6838                                              12002
6839                                              12241

      Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number)  \
0                                                  1045
1                                                  1055
2                                                  1075
3                                                  1103
4                                                  1134
...                                                 ...
6835                                               1063
6836                                               1082
6837                                               1098
6838                                               1117
6839                                               1140

      Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number)  \
0                                                  7077
1                                                  7149
2                                                  7297
3                                                  7499
4                                                  7698
...                                                 ...
6835                                               1354
6836                                               1383
6837                                               1409
6838                                               1439
6839                                               1475

      Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number)  \
0                                                   356
1                                                   364
2                                                   376
3                                                   389
4                                                   399
...                                                 ...
6835                                               4854
6836                                               4915
6837                                               4992
6838                                               5044
6839                                               5156

      Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number)  \
0                                                  3185
1                                                  3248
2                                                  3351
3                                                  3480
4                                                  3610
...                                                 ...
6835                                               1820
6836                                               1854
6837                                               1883
6838                                               1917
6839                                               1960

      Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number)  \
0                                                  3702
1                                                  4309
2                                                  5356
3                                                  7152
4                                                  7192
...                                                 ...
6835                                               4336
6836                                               4244
6837                                               4193
6838                                               4013
6839                                               3914

      ...  \
0     ...
1     ...
2     ...
3     ...
4     ...
...   ...
6835  ...
6836  ...
6837  ...
6838  ...
6839  ...

      Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number)  \
0                                                  9518
1                                                  9489
2                                                  9528
3                                                  9611
4                                                  9675
...                                                 ...
6835                                               5636
6836                                               5849
6837                                               6047
6838                                               6248
6839                                               6475

      Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number)  \
0                                                  2798
1                                                  3254
2                                                  4042
3                                                  5392
4                                                  5418
...                                                 ...
6835                                               2879
6836                                               2798
6837                                               2744
6838                                               2608
6839                                               2531

      Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number)  \
0                                                  4825
1                                                  5127
2                                                  5889
3                                                  7007
4                                                  7421
...                                                 ...
6835                                               4328
6836                                               4295
6837                                               4251
6838                                               4153
6839                                               4113

      Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number)  \
0                                                   174
1                                                   188
2                                                   211
3                                                   232
4                                                   247
...                                                 ...
6835                                               1068
6836                                               1042
6837                                               1007
6838                                                969
6839                                                963

      Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number)  \
0                                                   389
1                                                   389
2                                                   393
3                                                   411
4                                                   413
...                                                 ...
6835                                                407
6836                                                415
6837                                                424
6838                                                434
6839                                                438

      Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number)  \
0                                                  2016
1                                                  2056
2                                                  2100
3                                                  2316
4                                                  2665
...                                                 ...
6835                                                138
6836                                                101
6837                                                 82
6838                                                 85
6839                                                 81

      Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number)  \
0                                                  7686
1                                                  7886
2                                                  8568
3                                                  9875
4                                                 11031
...                                                 ...
6835                                                730
6836                                                674
6837                                                629
6838                                                607
6839                                                585

      Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)  \
0                                                   107
1                                                   121
2                                                   150
3                                                   204
4                                                   204
...                                                 ...
6835                                                 21
6836                                                 20
6837                                                 19
6838                                                 17
6839                                                 16

      Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)  \
0                                                  2216
1                                                  2501
2                                                  3053
3                                                  3726
4                                                  3833
...                                                 ...
6835                                                734
6836                                                700
6837                                                678
6838                                                644
6839                                                631

      Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)
0                                                   564
1                                                   611
2                                                   700
3                                                   773
4                                                   812
...                                                 ...
6835                                                282
6836                                                275
6837                                                267
6838                                                261
6839                                                259

[6840 rows x 31 columns]

In [21]:
# The total number of missing values in each column
df1.isna().sum()

Entity                                                                                                                0
Code                                                                                                                690
Year                                                                                                                  0
Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number)                  0
Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number)                  0
Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number)                           0
Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number)                      0
Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number)                                   0
Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number)                            0
Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number)                           0
Deaths - Cause: All causes - Risk: Secondhand smoke - Sex: Both - Age: All Ages (Number)                              0
Deaths - Cause: All causes - Risk: Low birth weight - Sex: Both - Age: All Ages (Number)                              0
Deaths - Cause: All causes - Risk: Child wasting - Sex: Both - Age: All Ages (Number)                                 0
Deaths - Cause: All causes - Risk: Unsafe sex - Sex: Both - Age: All Ages (Number)                                    0
Deaths - Cause: All causes - Risk: Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number)                    0
Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)      0
Deaths - Cause: All causes - Risk: Diet low in vegetables - Sex: Both - Age: All Ages (Number)                        0
Deaths - Cause: All causes - Risk: Low physical activity - Sex: Both - Age: All Ages (Number)                         0
Deaths - Cause: All causes - Risk: Smoking - Sex: Both - Age: All Ages (Number)                                       0
Deaths - Cause: All causes - Risk: High fasting plasma glucose - Sex: Both - Age: All Ages (Number)                   0
Deaths - Cause: All causes - Risk: Air pollution - Sex: Both - Age: All Ages (Number)                                 0
Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number)                          0
Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number)                             0
Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number)             0
Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number)                                      0
Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number)                      0
Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number)                          0
Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number)                                0
Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)                    0
Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)                   0
Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)                               0
dtype: int64

In [22]:
# Check the percentage of missing value in each column
# High total cholesterol is appoximately 76% missing values and 1 missing value in High total cholesterol
round(df.isnull().sum()/len(df1),4)

Entity                                                                                                              0.0000
Code                                                                                                                0.1009
Year                                                                                                                0.0000
Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number)                0.0000
Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number)                0.0000
Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number)                         0.0000
Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number)                    0.0000
Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number)                                 0.0000
Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number)                          0.0000
Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number)                         0.0000
Deaths - Cause: All causes - Risk: Secondhand smoke - Sex: Both - Age: All Ages (Number)                            0.0000
Deaths - Cause: All causes - Risk: Low birth weight - Sex: Both - Age: All Ages (Number)                            0.0000
Deaths - Cause: All causes - Risk: Child wasting - Sex: Both - Age: All Ages (Number)                               0.0000
Deaths - Cause: All causes - Risk: Unsafe sex - Sex: Both - Age: All Ages (Number)                                  0.0000
Deaths - Cause: All causes - Risk: Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number)                  0.0000
Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)    0.0000
Deaths - Cause: All causes - Risk: Diet low in vegetables - Sex: Both - Age: All Ages (Number)                      0.0000
Deaths - Cause: All causes - Risk: Low physical activity - Sex: Both - Age: All Ages (Number)                       0.0000
Deaths - Cause: All causes - Risk: Smoking - Sex: Both - Age: All Ages (Number)                                     0.0000
Deaths - Cause: All causes - Risk: High fasting plasma glucose - Sex: Both - Age: All Ages (Number)                 0.0000
Deaths - Cause: All causes - Risk: Air pollution - Sex: Both - Age: All Ages (Number)                               0.0000
Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number)                        0.0000
Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number)                           0.0000
Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number)           0.0000
Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number)                                    0.0000
Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number)                    0.0000
Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number)                        0.0000
Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number)                              0.0000
Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)                  0.0000
Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)                 0.0000
Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)                             0.0000
dtype: float64